services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=false"
      - "--providers.file.filename=/etc/traefik/dynamic_conf.yml"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "8088:8080" # Dashboard (Moved to 8088 to avoid 8080, 8081, 8082 conflicts)
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik_dynamic.yml:/etc/traefik/dynamic_conf.yml:ro"
    networks:
      - traefik-public
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --url http://traefik:80
    networks:
      - traefik-public
    restart: always

networks:
  traefik-public:
    external: true
